module Month
  module Serializer
    module Version
      VERSION: String
    end
    VERSION: String
  end
end

class Month
  module Serializer
    module Version
      VERSION: String
    end
    VERSION: String
  end
end
