---
# Lock/Unlock Deps Pattern
#
# Two often conflicting goals resolved!
#
#  - deps_unlocked.yml
#    - All runtime & dev dependencies, but does not have a `gemfiles/*.gemfile.lock` committed
#    - Uses an Appraisal2 "deps_unlocked" gemfile, and the current MRI Ruby release
#    - Know when new dependency releases will break local dev with unlocked dependencies
#    - Broken workflow indicates that new releases of dependencies may not work
#
#  - deps_locked.yml
#    - All runtime & dev dependencies, and has a `Gemfile.lock` committed
#    - Uses the project's main Gemfile, and the current MRI Ruby release
#    - Matches what contributors and maintainers use locally for development
#    - Broken workflow indicates that a new contributor will have a bad time
#
name: Deps Locked

permissions:
  contents: read

env:
  KITCHEN_SINK: true
  K_SOUP_COV_MIN_BRANCH: 60
  K_SOUP_COV_MIN_LINE: 77
  K_SOUP_COV_MIN_HARD: false
  K_SOUP_COV_FORMATTERS: "html,xml,rcov,lcov,tty"
  K_SOUP_COV_DO: true
  K_SOUP_COV_MULTI_FORMATTERS: true
  K_SOUP_COV_COMMAND_NAME: "Test Coverage"

on:
  push:
    branches:
      - 'main'
      - '*-stable'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Default rake task w/ main Gemfile.lock ${{ matrix.name_extra || '' }}
    if: ${{ !contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ruby <whichever version is current, e.g., 3.4 as of 2025-07-12>
          - ruby: "ruby"
            exec_cmd: "rake"
            rubygems: latest
            bundler: latest
            experimental: false

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true

      - name: Checks the kitchen sink via ${{ matrix.exec_cmd }}
        run: bundle exec ${{ matrix.exec_cmd }}
      - name: Upload coverage to Coveralls
        if: ${{ !env.ACT }}
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/lcov.info
          format: lcov
          fail-on-error: false
        continue-on-error: true

      - name: Upload coverage to QLTY
        if: ${{ !env.ACT }}
        uses: qltysh/qlty-action/coverage@08a0a862c159eae9b9003081da6663d96efef637 # v2.3.0
        with:
          oidc: true
          files: coverage/lcov.info
          format: lcov
          skip-errors: true
        continue-on-error: true

      - name: Upload coverage to CodeCov
        if: ${{ !env.ACT }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          use_oidc: true
          disable_search: true
          fail_ci_if_error: false
          files: coverage/lcov.info,coverage/coverage.xml
          verbose: true
        continue-on-error: true

      - name: Code Coverage Summary Report
        if: ${{ !env.ACT && github.event_name == 'pull_request' }}
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 # v1.3.0
        with:
          filename: ./coverage/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '${{ env.K_SOUP_COV_MIN_LINE }} ${{ env.K_SOUP_COV_MIN_BRANCH }}'
        continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        if: ${{ !env.ACT && github.event_name == 'pull_request' }}
        with:
          recreate: true
          path: code-coverage-results.md
        continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
